---
- hosts: all
  remote_user: vagrant
  become: yes
  gather_facts: true
  vars:
    - repo: "etc/yum.repos.d/virt7-docker-common-release.repo"
  tasks:
    - name: copy kubernetes config 
      template:
         src: "{{repo}}"
         dest: "/{{repo}}"
         owner: root
         group: root
         mode: 0644
      register: output
    - debug: msg="{{output}}"
    - name: check for updates (yum)
      yum: list=update update_cache=true
      register: yumoutput
    - debug: msg="{{yumoutput}}"
    - name: Clean up 
      shell: "yum-complete-transaction --cleanup-only"
      register: yumoutput
    - debug: msg="{{yumoutput}}"
    - name: Install packages
      yum: name="{{ item }}" state=present
      register: installOutput
      with_items:
        - kubernetes
        - docker
        - emacs-nox
        - nmap
        - etcd
        - ntp
        - git
        - lynx
    - debug:
      msg: "Output=>{{installOutput}}"
    - name: Disable Firewall
      systemd:
        name: firewalld
        enabled: no
        state: stopped
      register: output
    - debug: msg="Output=>{{output}}"
    - name: Replace SELINUX=disabled 
      replace:
        dest: /etc/selinux/config
        regexp: '^SELINUX=.*$'
        replace: 'SELINUX=disabled'
        validate: "grep 'SELINUX=disabled' %s" 
    - name: Reboot
      shell: "reboot now"
      when:  reboot is defined     
    
...
  